[package]
name = "lonelybot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lonelybot"
path = "src/lib.rs"

[[bin]]
name = "lonelybot-cli"
path = "src/bin.rs"

[lints.rust]
unsafe_code = "forbid"


[dependencies]
colored = "2.1.0"
rand = "0.8.5"
concat-arrays = "0.1.2"
quick_cache = "0.4.0"
bpci = "0.1.0"
signal-hook = "0.3.17"
criterion = "0.5.1"

[profile.release]
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.dev]
opt-level = 1               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.
lto = "thin"

[[bench]]
name = "gen_moves"
harness = false
